In [1]:
#NumPy, which stands for Numerical Python
# Using NumPy, mathematical and logical operations on arrays can be performed.
import numpy as np

In [2]:
np.__version__

'1.14.0'

In [7]:
L=list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
#Operations related to linear algebra. NumPy has in-built functions for linear algebra and random number generation.
type(L)

list

In [13]:
[str(c) for c in L]   # convert int to str

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [14]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.full((3,5),2.5)

array([[2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5],
       [2.5, 2.5, 2.5, 2.5, 2.5]])

In [17]:
np.linspace(0,1,5)#create an array of even space between the given range of values

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
np.random.normal(0,1,(3,3))

array([[ 1.05911475, -1.6956298 ,  1.32794888],
       [ 1.81251245,  0.42024771, -0.11095163],
       [-0.12480718,  2.13636567, -1.79087452]])

In [19]:
np.eye(3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
x1=np.array([4,5,4,8,2,5])

In [21]:
x1

array([4, 5, 4, 8, 2, 5])

In [22]:
x=np.arange(10)

In [20]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
x[:5]

array([0, 1, 2, 3, 4])

In [22]:
x[4:]

array([4, 5, 6, 7, 8, 9])

In [23]:
x[4:7]

array([4, 5, 6])

In [25]:
x[: : 2]

array([0, 2, 4, 6, 8])

In [26]:
x[1::2]

array([1, 3, 5, 7, 9])

In [27]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [28]:
x=np.array([1,2,3])

In [29]:
y=np.array([5,6,7])

In [30]:
z=[22,21,23]

In [32]:
np.concatenate([x,y,z])

array([ 1,  2,  3,  5,  6,  7, 22, 21, 23])

In [33]:
grid=np.array([[5,5,6],[7,4,8]])

In [34]:
grid

array([[5, 5, 6],
       [7, 4, 8]])

In [35]:
np.concatenate([grid,grid])

array([[5, 5, 6],
       [7, 4, 8],
       [5, 5, 6],
       [7, 4, 8]])

In [36]:
np.concatenate([grid,grid],axis=1)

array([[5, 5, 6, 5, 5, 6],
       [7, 4, 8, 7, 4, 8]])

In [37]:
x=np.array([5,6,7])
grid=np.array([[8,9,7],[1,2,3]])
np.vstack([x,grid])

array([[5, 6, 7],
       [8, 9, 7],
       [1, 2, 3]])

In [40]:
x=np.arange(10)
x1,x2,x3=np.split(x,[3,6])

In [43]:
x1

array([0, 1, 2])

In [44]:
x2

array([3, 4, 5])

In [45]:
x3

array([6, 7, 8, 9])

In [46]:
#  let's' start with pandas

In [47]:
# PANDAS FOR MACHINE LEARNING

In [24]:
import pandas as pd
import numpy as np

In [25]:
data=pd.DataFrame({'Country':['Russia','Colombia','chile','Equador','Nigeria'],'Value':[121,40,100,30,121]})

In [26]:
data

Country  Value
0    Russia    121
1  Colombia     40
2     chile    100
3   Equador     30
4   Nigeria    121

In [27]:
data.describe()

Value
count    5.000000
mean    82.400000
std     44.252684
min     30.000000
25%     40.000000
50%    100.000000
75%    121.000000
max    121.000000

In [28]:
data.info()  # to get coplete information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
Country    5 non-null object
Value      5 non-null int64
dtypes: int64(1), object(1)
memory usage: 160.0+ bytes


In [30]:
data = pd.DataFrame({'group':['a', 'a', 'a', 'b','b', 'b', 'c', 'c','c'],'ounces':[4, 3, 12, 8, 7.5, 5, 7, 5, 6]})

In [31]:
data

group  ounces
0     a     4.0
1     a     3.0
2     a    12.0
3     b     8.0
4     b     7.5
5     b     5.0
6     c     7.0
7     c     5.0
8     c     6.0

In [32]:
data.sort_values(by=['ounces'],ascending=True,inplace=False)

group  ounces
1     a     3.0
0     a     4.0
5     b     5.0
7     c     5.0
8     c     6.0
6     c     7.0
4     b     7.5
3     b     8.0
2     a    12.0

In [69]:
data.sort_values(by=['group','ounces'],ascending=['True','False'],inplace=False)

group  ounces
1     a     3.0
0     a     4.0
2     a    12.0
5     b     5.0
4     b     7.5
3     b     8.0
7     c     5.0
8     c     6.0
6     c     7.0

In [71]:
data=pd.DataFrame({'k1':['one']*3+['two']*4,'k2':[3,2,1,3,3,4,4]})

In [72]:
data

k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
4  two   3
5  two   4
6  two   4

In [73]:
data.sort_values(by='k2')

k1  k2
2  one   1
1  one   2
0  one   3
3  two   3
4  two   3
5  two   4
6  two   4

In [74]:
data.drop_duplicates()

k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
5  two   4

In [75]:
data.drop_duplicates(subset='k1')

k1  k2
0  one   3
3  two   3

In [76]:
data=pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami','corned beef', 'Bacon', 'pastrami', 'honey ham','nova lox'],
                 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [77]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [79]:
meat_to_animal = {
'bacon': 'pig',
'pulled pork': 'pig',
'pastrami': 'cow',
'corned beef': 'cow',
'honey ham': 'pig',
'nova lox': 'salmon'
}


In [80]:
meat_to_animal

{'bacon': 'pig',
 'corned beef': 'cow',
 'honey ham': 'pig',
 'nova lox': 'salmon',
 'pastrami': 'cow',
 'pulled pork': 'pig'}

In [81]:
data['animal'] = data['food'].map(str.lower).map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [2]:
data.assign(new_var=data['ounces']*10)

NameError: name 'data' is not defined

In [83]:
df = pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'],
                   'key2' : ['one', 'two', 'one', 'two', 'one'],
                   'data1' : np.random.randn(5),
                   'data2' : np.random.randn(5)})

In [85]:
df

data1     data2 key1 key2
0  2.450676 -0.212955    a  one
1  0.178612 -0.607668    a  two
2  0.313007 -0.005626    b  one
3 -0.691567  1.661227    b  two
4  1.507988  0.195025    a  one

In [86]:
df[:3]

data1     data2 key1 key2
0  2.450676 -0.212955    a  one
1  0.178612 -0.607668    a  two
2  0.313007 -0.005626    b  one

In [87]:
df[2:]

data1     data2 key1 key2
2  0.313007 -0.005626    b  one
3 -0.691567  1.661227    b  two
4  1.507988  0.195025    a  one

In [35]:
dates = pd.date_range('20180607',periods=6)
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))


In [36]:
df

A         B         C         D
2018-06-07 -2.221984 -0.206259  0.378561 -0.498655
2018-06-08  0.241669 -0.337515 -1.377107 -1.293804
2018-06-09 -0.508383 -0.045951  0.583888 -0.386562
2018-06-10 -0.303568  0.207465 -0.260663  0.092889
2018-06-11  0.386825  0.365096  0.319633  2.394813
2018-06-12  1.534590  1.494817  0.761698  1.839149

In [37]:
df['20180609':'20180612']


A         B         C         D
2018-06-09 -0.508383 -0.045951  0.583888 -0.386562
2018-06-10 -0.303568  0.207465 -0.260663  0.092889
2018-06-11  0.386825  0.365096  0.319633  2.394813
2018-06-12  1.534590  1.494817  0.761698  1.839149

In [38]:
df.loc[:,['A','B']]


A         B
2018-06-07 -2.221984 -0.206259
2018-06-08  0.241669 -0.337515
2018-06-09 -0.508383 -0.045951
2018-06-10 -0.303568  0.207465
2018-06-11  0.386825  0.365096
2018-06-12  1.534590  1.494817

In [39]:
df.loc['20180607':'20180610',['A','B']]


A         B
2018-06-07 -2.221984 -0.206259
2018-06-08  0.241669 -0.337515
2018-06-09 -0.508383 -0.045951
2018-06-10 -0.303568  0.207465

In [100]:
df.iloc[3]

A   -0.395587
B   -0.004521
C   -0.325041
D    0.879185
Name: 2018-06-10 00:00:00, dtype: float64

In [102]:
df.iloc[[1,5],[0,2]] 

A         C
2018-06-08 -0.302968  0.115053
2018-06-12  1.725406  0.290249

In [103]:
df[df.A>1]

A       B         C         D
2018-06-12  1.725406  0.0555  0.290249 -0.510809

In [41]:
df2=df.copy()

In [46]:
df2['E']=['one', 'one','two','three','four','three']

In [47]:
df2

A         B         C         D      E
2018-06-07 -2.221984 -0.206259  0.378561 -0.498655    one
2018-06-08  0.241669 -0.337515 -1.377107 -1.293804    one
2018-06-09 -0.508383 -0.045951  0.583888 -0.386562    two
2018-06-10 -0.303568  0.207465 -0.260663  0.092889  three
2018-06-11  0.386825  0.365096  0.319633  2.394813   four
2018-06-12  1.534590  1.494817  0.761698  1.839149  three

In [48]:
#select rows based on column values
df2[df2['E'].isin(['one','two'])]

A         B         C         D    E
2018-06-07 -2.221984 -0.206259  0.378561 -0.498655  one
2018-06-08  0.241669 -0.337515 -1.377107 -1.293804  one
2018-06-09 -0.508383 -0.045951  0.583888 -0.386562  two

In [110]:
df2[~df2['E'].isin(['one','three','two'])]

A         B        C         D     E
2018-06-11  0.649322 -1.137411  1.62236 -0.019578  four

In [114]:
df2.query('A>C')  #keep notice in A and C

A         B         C         D      E
2018-06-07 -0.690148  2.111006 -0.854157  0.027975    one
2018-06-12  1.725406  0.055500  0.290249 -0.510809  three

In [115]:
df.query('A<C | B<A')

A         B         C         D
2018-06-08 -0.302968 -0.104074  0.115053 -0.511520
2018-06-09 -2.839733 -0.445416 -0.201028 -0.869996
2018-06-10 -0.395587 -0.004521 -0.325041  0.879185
2018-06-11  0.649322 -1.137411  1.622360 -0.019578
2018-06-12  1.725406  0.055500  0.290249 -0.510809

In [116]:
data = pd.DataFrame({'group': ['a', 'a', 'a', 'b','b', 'b', 'c', 'c','c'],
                 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [117]:
data

group  ounces
0     a     4.0
1     a     3.0
2     a    12.0
3     b     6.0
4     b     7.5
5     b     8.0
6     c     3.0
7     c     5.0
8     c     6.0

In [118]:
data.pivot_table(values='ounces',index='group',aggfunc=min)

ounces
group        
a         3.0
b         6.0
c         3.0

In [119]:
data.pivot_table(values='ounces',index='group',aggfunc=np.mean)

ounces
group          
a      6.333333
b      7.166667
c      4.666667

In [120]:
data.pivot_table(values='ounces',index='group',aggfunc='count')

ounces
group        
a           3
b           3
c           3

In [122]:
train  = pd.read_csv("~/train.csv")


In [123]:
train

age          workclass  fnlwgt      education  education.num  \
0       39          State-gov   77516      Bachelors             13   
1       50   Self-emp-not-inc   83311      Bachelors             13   
2       38            Private  215646        HS-grad              9   
3       53            Private  234721           11th              7   
4       28            Private  338409      Bachelors             13   
5       37            Private  284582        Masters             14   
6       49            Private  160187            9th              5   
7       52   Self-emp-not-inc  209642        HS-grad              9   
8       31            Private   45781        Masters             14   
9       42            Private  159449      Bachelors             13   
10      37            Private  280464   Some-college             10   
11      30          State-gov  141297      Bachelors             13   
12      23            Private  122272      Bachelors             13   
13      32            Private  205019     Assoc-acdm             12   
14      40            Private  121772      Assoc-voc             11   
15      34            Private  245487        7th-8th              4   
16      25   Self-emp-not-inc  176756        HS-grad              9   
17      32            Private  186824        HS-grad              9   
18      38            Private   28887           11th              7   
19      43   Self-emp-not-inc  292175        Masters             14   
20      40            Private  193524      Doctorate             16   
21      54            Private  302146        HS-grad              9   
22      35        Federal-gov   76845            9th              5   
23      43            Private  117037           11th              7   
24      59            Private  109015        HS-grad              9   
25      56          Local-gov  216851      Bachelors             13   
26      19            Private  168294        HS-grad              9   
27      54                NaN  180211   Some-college             10   
28      39            Private  367260        HS-grad              9   
29      49            Private  193366        HS-grad              9   
...    ...                ...     ...            ...            ...   
32531   30                NaN   33811      Bachelors             13   
32532   34            Private  204461      Doctorate             16   
32533   54            Private  337992      Bachelors             13   
32534   37            Private  179137   Some-college             10   
32535   22            Private  325033           12th              8   
32536   34            Private  160216      Bachelors             13   
32537   30            Private  345898        HS-grad              9   
32538   38            Private  139180      Bachelors             13   
32539   71                NaN  287372      Doctorate             16   
32540   45          State-gov  252208        HS-grad              9   
32541   41                NaN  202822        HS-grad              9   
32542   72                NaN  129912        HS-grad              9   
32543   45          Local-gov  119199     Assoc-acdm             12   
32544   31            Private  199655        Masters             14   
32545   39          Local-gov  111499     Assoc-acdm             12   
32546   37            Private  198216     Assoc-acdm             12   
32547   43            Private  260761        HS-grad              9   
32548   65   Self-emp-not-inc   99359    Prof-school             15   
32549   43          State-gov  255835   Some-college             10   
32550   43   Self-emp-not-inc   27242   Some-college             10   
32551   32            Private   34066           10th              6   
32552   43            Private   84661      Assoc-voc             11   
32553   32            Private  116138        Masters             14   
32554   53            Private  321865        Masters             14   
32555   22            Private  

In [125]:
test = pd.read_csv("~/test.csv")


In [126]:
test

age          workclass  fnlwgt      education  education.num  \
0       25            Private  226802           11th              7   
1       38            Private   89814        HS-grad              9   
2       28          Local-gov  336951     Assoc-acdm             12   
3       44            Private  160323   Some-college             10   
4       18                NaN  103497   Some-college             10   
5       34            Private  198693           10th              6   
6       29                NaN  227026        HS-grad              9   
7       63   Self-emp-not-inc  104626    Prof-school             15   
8       24            Private  369667   Some-college             10   
9       55            Private  104996        7th-8th              4   
10      65            Private  184454        HS-grad              9   
11      36        Federal-gov  212465      Bachelors             13   
12      26            Private   82091        HS-grad              9   
13      58                NaN  299831        HS-grad              9   
14      48            Private  279724        HS-grad              9   
15      43            Private  346189        Masters             14   
16      20          State-gov  444554   Some-college             10   
17      43            Private  128354        HS-grad              9   
18      37            Private   60548        HS-grad              9   
19      40            Private   85019      Doctorate             16   
20      34            Private  107914      Bachelors             13   
21      34            Private  238588   Some-college             10   
22      72                NaN  132015        7th-8th              4   
23      25            Private  220931      Bachelors             13   
24      25            Private  205947      Bachelors             13   
25      45   Self-emp-not-inc  432824        HS-grad              9   
26      22            Private  236427        HS-grad              9   
27      23            Private  134446        HS-grad              9   
28      54            Private   99516        HS-grad              9   
29      32   Self-emp-not-inc  109282   Some-college             10   
...    ...                ...     ...            ...            ...   
16251   81                NaN   26711      Assoc-voc             11   
16252   60            Private  117909      Assoc-voc             11   
16253   39            Private  229647      Bachelors             13   
16254   38            Private  149347        Masters             14   
16255   43          Local-gov   23157        Masters             14   
16256   23            Private   93977        HS-grad              9   
16257   73       Self-emp-inc  159691   Some-college             10   
16258   35            Private  176967   Some-college             10   
16259   66            Private  344436        HS-grad              9   
16260   27            Private  430340   Some-college             10   
16261   40            Private  202168    Prof-school             15   
16262   51            Private   82720        HS-grad              9   
16263   22            Private  269623   Some-college             10   
16264   64   Self-emp-not-inc  136405        HS-grad              9   
16265   50          Local-gov  139347        Masters             14   
16266   55            Private  224655        HS-grad              9   
16267   38            Private  247547      Assoc-voc             11   
16268   58            Private  292710     Assoc-acdm             12   
16269   32            Private  173449        HS-grad              9   
16270   48            Private  285570        HS-grad              9   
16271   61            Private   89686        HS-grad              9   
16272   31            Private  440129        HS-grad              9   
16273   25            Private  350977        HS-grad              9   
16274   48          Local-gov  349230        Masters             14   
16275   33            Private  

In [127]:
train.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
age               32561 non-null int64
workclass         30725 non-null object
fnlwgt            32561 non-null int64
education         32561 non-null object
education.num     32561 non-null int64
marital.status    32561 non-null object
occupation        30718 non-null object
relationship      32561 non-null object
race              32561 non-null object
sex               32561 non-null object
capital.gain      32561 non-null int64
capital.loss      32561 non-null int64
hours.per.week    32561 non-null int64
native.country    31978 non-null object
target            32561 non-null object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [129]:
print ("The train data has",train.shape)
print ("The test data has",test.shape)
       

The train data has (32561, 15)
The test data has (16281, 15)


In [130]:
train.head()

age          workclass  fnlwgt   education  education.num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        marital.status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital.gain  capital.loss  hours.per.week  native.country  target  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [131]:
test.head()

age   workclass  fnlwgt      education  education.num       marital.status  \
0   25     Private  226802           11th              7        Never-married   
1   38     Private   89814        HS-grad              9   Married-civ-spouse   
2   28   Local-gov  336951     Assoc-acdm             12   Married-civ-spouse   
3   44     Private  160323   Some-college             10   Married-civ-spouse   
4   18         NaN  103497   Some-college             10        Never-married   

           occupation relationship    race      sex  capital.gain  \
0   Machine-op-inspct    Own-child   Black     Male             0   
1     Farming-fishing      Husband   White     Male             0   
2     Protective-serv      Husband   White     Male             0   
3   Machine-op-inspct      Husband   Black     Male          7688   
4                 NaN    Own-child   White   Female             0   

   capital.loss  hours.per.week  native.country   target  
0             0              40   United-States   <=50K.  
1             0              50   United-States   <=50K.  
2             0              40   United-States    >50K.  
3             0              40   United-States    >50K.  
4             0              30   United-States   <=50K.

In [132]:
nans = train.shape[0] - train.dropna().shape[0]
print ("%d rows have missing values in the train data" %nans)

nand = test.shape[0] - test.dropna().shape[0]
print ("%d rows have missing values in the test data" %nand)


2399 rows have missing values in the train data
1221 rows have missing values in the test data


In [133]:
train.isnull().sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education.num        0
marital.status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital.gain         0
capital.loss         0
hours.per.week       0
native.country     583
target               0
dtype: int64

In [134]:
cat = train.select_dtypes(include=['O'])
cat.apply(pd.Series.nunique)

workclass          8
education         16
marital.status     7
occupation        14
relationship       6
race               5
sex                2
native.country    41
target             2
dtype: int64

In [135]:
#check proportion of target variable
train.target.value_counts()/train.shape[0]

 <=50K    0.75919
 >50K     0.24081
Name: target, dtype: float64

In [136]:
pd.crosstab(train.education, train.target,margins=True)/train.shape[0]


target            <=50K      >50K       All
education                                  
 10th          0.026750  0.001904  0.028654
 11th          0.034243  0.001843  0.036086
 12th          0.012285  0.001013  0.013298
 1st-4th       0.004975  0.000184  0.005160
 5th-6th       0.009736  0.000491  0.010227
 7th-8th       0.018611  0.001228  0.019840
 9th           0.014957  0.000829  0.015786
 Assoc-acdm    0.024631  0.008139  0.032769
 Assoc-voc     0.031357  0.011087  0.042443
 Bachelors     0.096250  0.068210  0.164461
 Doctorate     0.003286  0.009398  0.012684
 HS-grad       0.271060  0.051442  0.322502
 Masters       0.023464  0.029452  0.052916
 Preschool     0.001566  0.000000  0.001566
 Prof-school   0.004699  0.012991  0.017690
 Some-college  0.181321  0.042597  0.223918
All            0.759190  0.240810  1.000000

In [139]:
from sklearn import preprocessing

for x in train.columns:
    if train[x].dtype == 'object':
        lbl = preprocessing.LabelEncoder()
        lbl.fit(list(train[x].values))
        train[x] = lbl.transform(list(train[x].values))

In [140]:
train.head()

age  workclass  fnlwgt  education  education.num  marital.status  \
0   39          6   77516          9             13               4   
1   50          5   83311          9             13               2   
2   38          3  215646         11              9               0   
3   53          3  234721          1              7               2   
4   28          3  338409          9             13               2   

   occupation  relationship  race  sex  capital.gain  capital.loss  \
0           0             1     4    1          2174             0   
1           3             0     4    1             0             0   
2           5             1     4    1             0             0   
3           5             0     2    1             0             0   
4           9             5     2    0             0             0   

   hours.per.week  native.country  target  
0              40              38       0  
1              13              38       0  
2              40              38       0  
3              40              38       0  
4              40               4       0

In [142]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.cross_validation import cross_val_score
from sklearn.metrics import accuracy_score

y = train['target']
del train['target']

X = train
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=1,stratify=y)

#train the RF classifier
clf = RandomForestClassifier(n_estimators = 500, max_depth = 6)
clf.fit(X_train,y_train)
RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                max_depth=6, max_features='auto', max_leaf_nodes=None,
                min_impurity_split=1e-07, min_samples_leaf=1,
                min_samples_split=2, min_weight_fraction_leaf=0.0,
                n_estimators=500, n_jobs=1, oob_score=False, random_state=None,
                verbose=0, warm_start=False)

clf.predict(X_test)

C:\Users\Rose\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [1]:
%matplotlib inline